#server:
#  port: 8130 # 服务端口
#
#spring:
#  profiles:
#    active: dev # 环境设置
#  application:
#    name: service-oss # 服务名
#
#aliyun:
#  oss:
#    endpoint: oss-cn-bei
#    keyId: LTAI4GKauWVZy
#    keySecret: ri4WsW
#    bucketName: dlq-jr
